package entity;
// Generated Oct 10, 2016 5:51:38 PM by Hibernate Tools 4.3.1



/**
 * Categoryproperty generated by hbm2java
 */
public class Categoryproperty  implements java.io.Serializable {


     private Integer id;
     private Integer catId;
     private String name;
     private String status;

    public Categoryproperty() {
    }

    public Categoryproperty(Integer catId, String name, String status) {
       this.catId = catId;
       this.name = name;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


