package entity;
// Generated Jun 14, 2017 2:13:46 PM by Hibernate Tools 4.3.1



/**
 * Orderdetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private Integer id;
     private Integer orderId;
     private Integer productId;
     private Float price;
     private Integer quantity;
     private String status;

    public OrderDetail() {
    }

    public OrderDetail(Integer orderId, Integer productId, Float price, Integer quantity, String status) {
       this.orderId = orderId;
       this.productId = productId;
       this.price = price;
       this.quantity = quantity;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


