package entity;
// Generated Oct 28, 2016 9:29:03 AM by Hibernate Tools 4.3.1



/**
 * ProductpropertydetailId generated by hbm2java
 */
public class ProductPropertyDetailId  implements java.io.Serializable {


     private int propertyId;
     private int productId;

    public ProductPropertyDetailId() {
    }

    public ProductPropertyDetailId(int propertyId, int productId) {
       this.propertyId = propertyId;
       this.productId = productId;
    }
   
    public int getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(int propertyId) {
        this.propertyId = propertyId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductPropertyDetailId) ) return false;
		 ProductPropertyDetailId castOther = ( ProductPropertyDetailId ) other; 
         
		 return (this.getPropertyId()==castOther.getPropertyId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPropertyId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


