package entity;
// Generated Oct 10, 2016 5:51:38 PM by Hibernate Tools 4.3.1



/**
 * ProductpropertydetailId generated by hbm2java
 */
public class ProductpropertydetailId  implements java.io.Serializable {


     private int propertyId;
     private int productId;

    public ProductpropertydetailId() {
    }

    public ProductpropertydetailId(int propertyId, int productId) {
       this.propertyId = propertyId;
       this.productId = productId;
    }
   
    public int getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(int propertyId) {
        this.propertyId = propertyId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductpropertydetailId) ) return false;
		 ProductpropertydetailId castOther = ( ProductpropertydetailId ) other; 
         
		 return (this.getPropertyId()==castOther.getPropertyId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPropertyId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


