package entity;
// Generated Oct 10, 2016 5:51:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Float price;
     private String shopId;
     private Integer quantity;
     private Date createdAt;
     private Integer brandId;
     private String status;

    public Product() {
    }

    public Product(String name, Float price, String shopId, Integer quantity, Date createdAt, Integer brandId, String status) {
       this.name = name;
       this.price = price;
       this.shopId = shopId;
       this.quantity = quantity;
       this.createdAt = createdAt;
       this.brandId = brandId;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public String getShopId() {
        return this.shopId;
    }
    
    public void setShopId(String shopId) {
        this.shopId = shopId;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


