package entity;
// Generated Oct 17, 2016 10:00:42 AM by Hibernate Tools 4.3.1



/**
 * Rate generated by hbm2java
 */
public class Rate  implements java.io.Serializable {


     private Integer id;
     private Integer productId;
     private Integer rate;
     private String content;

    public Rate() {
    }

    public Rate(Integer productId, Integer rate, String content) {
       this.productId = productId;
       this.rate = rate;
       this.content = content;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


