package entity;
// Generated Nov 1, 2016 11:13:25 PM by Hibernate Tools 4.3.1



/**
 * Shop generated by hbm2java
 */
public class Shop  implements java.io.Serializable {


     private Integer id;
     private Integer userId;
     private String address;
     private String phone;
     private String email;
     private String status;
     private String name;
     private String facebook;

    public Shop() {
    }

    public Shop(Integer userId, String address, String phone, String email, String status, String name, String facebook) {
       this.userId = userId;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.status = status;
       this.name = name;
       this.facebook = facebook;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }




}


