package entity;
// Generated Sep 22, 2016 9:17:53 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long id;
     private String username;
     private String password;
     private String email;
     private String address;
     private String district;
     private String state;
     private String country;
     private byte status;
     private String passwordToken;

    public User() {
    }

	
    public User(String username, String password, String email, byte status) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.status = status;
    }
    public User(String username, String password, String email, String address, String district, String state, String country, byte status, String passwordToken) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.address = address;
       this.district = district;
       this.state = state;
       this.country = country;
       this.status = status;
       this.passwordToken = passwordToken;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public String getPasswordToken() {
        return this.passwordToken;
    }
    
    public void setPasswordToken(String passwordToken) {
        this.passwordToken = passwordToken;
    }




}


