package entity;
// Generated Nov 1, 2016 11:13:25 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String name;
     private String address;
     private String phone;
     private String email;
     private String status;
     private Byte userGroup;

    public User() {
    }

    public User(String username, String password, String name, String address, String phone, String email, String status, Byte userGroup) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.status = status;
       this.userGroup = userGroup;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Byte getUserGroup() {
        return this.userGroup;
    }
    
    public void setUserGroup(Byte userGroup) {
        this.userGroup = userGroup;
    }




}


